set(CMAKE_CXX_COMPILER "g++" CACHE STRING "")
set(CMAKE_C_COMPILER "gcc" CACHE STRING "")
set(CMAKE_Fortran_COMPILER "gfortran" CACHE STRING "")

set(YAKL_ARCH "OPENMP" CACHE STRING "")
set(YAKL_OPENMP_FLAGS "-O3 -mavx512f -fopenmp" CACHE STRING "")

set(OMEGA_USE_CXX_SIMD ON CACHE BOOL "")
set(OMEGA_VECTOR_LENGTH "8" CACHE STRING "")
