set(CMAKE_CXX_COMPILER "icpx" CACHE STRING "")
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "")
set(CMAKE_CXX_FLAGS "-Xclang -mlong-double-64" CACHE STRING "")

set(Kokkos_ENABLE_SERIAL ON CACHE BOOL "")
set(Kokkos_ENABLE_OPENMP OFF CACHE BOOL "")
set(Kokkos_ENABLE_SYCL ON CACHE BOOL "")

set(Kokkos_ARCH_SPR ON CACHE BOOL "")
set(Kokkos_ARCH_INTEL_GEN ON CACHE BOOL "")

set(Kokkos_ENABLE_ONEDPL OFF CACHE BOOL "")

set(OMEGA_USE_HIERARCHICAL OFF CACHE BOOL "")
