set(CMAKE_CXX_COMPILER "amdclang++" CACHE STRING "")
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "")

set(Kokkos_ENABLE_SERIAL ON CACHE BOOL "")
set(Kokkos_ENABLE_OPENMP ON CACHE BOOL "")

set(Kokkos_ARCH_ZEN3 ON CACHE BOOL "")

set(OMEGA_USE_HIERARCHICAL OFF CACHE BOOL "")
