set(CMAKE_CXX_COMPILER "g++" CACHE STRING "")
set(CMAKE_CUDA_HOST_COMPILER "g++" CACHE STRING "")
set(CMAKE_C_COMPILER "gcc" CACHE STRING "")
set(CMAKE_Fortran_COMPILER "gfortran" CACHE STRING "")

set(YAKL_ARCH "CUDA" CACHE STRING "")
set(YAKL_CUDA_FLAGS "-O3 -arch=sm_80" CACHE STRING "")
