set(CMAKE_CXX_COMPILER "icpx" CACHE STRING "")
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")

set(Kokkos_ENABLE_SERIAL ON CACHE BOOL "")
set(Kokkos_ENABLE_OPENMP OFF CACHE BOOL "")
set(Kokkos_ARCH_NATIVE ON CACHE BOOL "")
