set(CMAKE_CXX_COMPILER "clang++" CACHE STRING "")
set(CMAKE_C_COMPILER "clang" CACHE STRING "")
set(CMAKE_Fortran_COMPILER "gfortran" CACHE STRING "")

set(YAKL_ARCH "" CACHE STRING "")
set(YAKL_CXX_FLAGS "-O3" CACHE STRING "")

set(OMEGA_USE_CXX_SIMD OFF CACHE BOOL "")
set(OMEGA_VECTOR_LENGTH "4" CACHE STRING "")
